openapi: 3.0.0
info:
  description: This API rates and reviews movies
  version: 1.0.0
  title: Movie Recommendation API
tags:
  - name: users
    description: Operations available to regular users
paths:
  /movies/rate:
    post:
      tags:
        - users
      summary: reports a rate event
      operationId: app.rate
      description: submits movie ratings by movie id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieRating'
      responses:
        '201':
          description: rating submitted successfully
        '400':
          description: invalid input, rating failed
  /movies/save:
    post:
      tags:
        - users
      summary: Add a movie to a user's list
      operationId: app.save_movie
      description: Add a movie to a user's list by movie ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieSaveRequest'
      responses:
        '201':
          description: Movie saved successfully
        '400':
          description: invalid input, movie was not added
components:
  schemas:
    MovieRating:
      type: object
      properties:
        movie_id:
          type: string
          example: breaking_bad_01
        movie_name:
          type: string
          example: Breaking Bad
        rating:
          type: number
          example: 10
        review:
          type: string
          example: its great yall
      required:
        - movie_id
        - rating
        - review
    MovieSaveRequest:
      type: object
      properties:
        user_id:
          type: number
          example: 19238902
        movie_id:
          type: string
          example: breaking_bad
        save_date:
          type: string
          format: date
          example: '2023-08-09'
        notes:
          type: string
          example: "Must-watch series"
        season:
          type: number
          example: 1
      required:
        - user_id
        - movie_id
        - season